- name: Send email to instructor with inventroy attached
  delegate_to: localhost
  sendgrid:
    username: "{{ sendgrid_user | default(omit) }}"
    password: "{{ sendgrid_pass | default(omit) }}"
    api_key: "{{ sendgrid_api_key | default(omit) }}"
    subject: "[Ansible] Important Training Details"
    body: |
          Attached is the Ansible inventory to be used for training.<br>
          Please check your ability to connect to each of the hosts via ssh.<br>
          {% if 'hosting_nodes' in groups %}
          {% if hosted_zone_domain_name is defined %}
          Log in to: http://{{ ec2_name_prefix | lower }}.{{ hosted_zone_domain_name }}<br>
          {% endif %}
          {% endif %}

    to_addresses: "{{ instructor_email }}"
    html_body: yes
    from_address: "{{ instructor_email }}"
    attachments:
      - "instructor_inventory.txt"
      - "index.html"
  when: email and instructor_email is defined
  tags:
    - email
