---
# handlers file for joe-speedboat.guacamole

- name: restart tomcat
  systemd:
    name: tomcat
    state: restarted
    enabled: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: reboot
  shell: sleep 2 && reboot
  async: 30
  poll: 0
