---
# tasks file for joe-speedboat.guacamole

- name: Install packages
  include_tasks: install-packages-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Create temp directory
  file:
    path: '{{ guacamole_temp_path }}'
    state: directory
  changed_when: False

- name: Install and configure mariadb
  include_tasks: mariadb.yml

- name: Install guacamole server
  include_tasks: install-guacamole-server.yml

- name: Install guacamole client
  include_tasks: install-guacamole-client.yml

- name: Configure database
  include_tasks: configure-database.yml

- name: Configure guacamole
  include_tasks: configure-guacamole.yml

- name: Start and enable guacd on startup
  systemd: 
    name: guacd
    state: started
    enabled: yes
    daemon_reload: yes

- name: Clean up temporary files
  file:
    path: '{{ guacamole_temp_path }}'
    state: absent
  changed_when: False

- name: Install/configure nginx 
  include_tasks: setup-nginx-redhat.yml
  when: nginx_ssl_reverse_proxy
