- name: manage s3 bucket
  s3_bucket:
    name: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone | lower }}"
    state: "{{ s3_state }}"
    region: "{{ ec2_region }}"
    force: yes

- name: dns for landing page (Route 53)
  route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}"
    type: CNAME
    overwrite: yes
    value: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}.s3-website{{ '-' if ec2_region == 'us-east-1' else '.'}}{{ ec2_region }}.amazonaws.com"
  when: dns_provider == 'route53'

- name: dns for landing page (DNS Made Easy)
  dnsmadeeasy:
    account_key: "{{dme_account_key}}"
    account_secret: "{{dme_account_secret}}"
    domain: "{{workshop_dns_zone}}"
    record_name: "{{ ec2_name_prefix | lower }}"
    record_ttl: "600"
    record_type: CNAME
    record_value: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}.s3-website{{ '-' if ec2_region == 'us-east-1' else '.'}}{{ ec2_region }}.amazonaws.com"
    state: "{{ s3_state }}"
  when: dns_provider == 'dme'

- block:
  - name: enable web hosting on bucket
    s3_website:
      name: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone | lower }}"
      state: "{{ s3_state }}"
      region: "{{ ec2_region }}"
      suffix: 'index.html'
    register: s3_site

  - name: PUT landing page
    s3_sync:
      bucket: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}"
      region: "{{ ec2_region }}"
      file_root: ./
      mime_map:
        .html: text/html
      permission: public-read
      include: 'index.html'

  - name: PUT decks
    s3_sync:
      bucket: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}"
      region: "{{ ec2_region }}"
      file_root: ../decks/
      mime_map:
        .html: text/html
        .svg: image/svg+xml
      permission: public-read
      key_prefix: decks
      include: '*'

  - name: Write License Local
    copy:
      content: "{{ tower_license }}"
      dest: ./license.txt

  - name: PUT License
    s3_sync:
      bucket: "{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}"
      region: "{{ ec2_region }}"
      file_root: ./
      permission: public-read
      include: 'license.txt'

  - name: Remove License from Local
    file:
      path: ./license.txt
      state: absent

  - name: output url
    debug:
      msg: 'landing page is available at http://{{ ec2_name_prefix | lower }}.{{ workshop_dns_zone }}/'

  when: s3_state == 'present'
