- name: Wait for instances to finish initializing
  pause:
    seconds: 90
  when: instances is changed
  tags:
    - always
    - provision

- name: Waiting for servers to come online
  wait_for: host="{{ item.tagged_instances[0].public_ip }}" port="{{ ssh_port }}" search_regex=OpenSSH
  with_items: "{{ instances.results }}"
  when: instances | changed
  tags:
    - always
    - provision

- name: Add hosts to control_nodes group
  add_host:
    name: "{{ item.invocation.module_args.instance_tags.Name }}"
    ansible_host: "{{ item.tagged_instances[0].public_ip }}"
<<<<<<< HEAD:aws_lab_setup/roles/manage_ec2_instances/tasks/create.yml
    ansible_user: "{{ ec2_login_names[item.item.item.1.type] }}"
    ansible_port: "{{ ssh_port }}"
=======
    ansible_user: "{{ ec2_login_names[item.item.1.type] }}"
    ansible_port: "{{ ssh_port | default('22') }}"
>>>>>>> e746bfd9b9579dc2b619b2e6de802639accbfee3:tools/aws_lab_setup/roles/manage_ec2_instances/tasks/create.yml
    groups: lab_hosts,control_nodes
  with_items: "{{ instances.results }}"
  when: "'ansible' in item.invocation.module_args.instance_tags.Name"
  changed_when: no
  tags:
    - always
    - provision

- name: Add hosts to groups
  add_host:
    name: "{{ item.invocation.module_args.instance_tags.Name }}"
    ansible_host: "{{ item.tagged_instances[0].public_ip }}"
<<<<<<< HEAD:aws_lab_setup/roles/manage_ec2_instances/tasks/create.yml
    ansible_user: "{{ ec2_login_names[item.item.item.1.type] }}"
    ansible_port: "{{ ssh_port }}"
=======
    ansible_user: "{{ ec2_login_names[item.item.1.type] }}"
    ansible_port: "{{ ssh_port | default('22') }}"
>>>>>>> e746bfd9b9579dc2b619b2e6de802639accbfee3:tools/aws_lab_setup/roles/manage_ec2_instances/tasks/create.yml
    groups: lab_hosts,managed_nodes
  with_items: "{{ instances.results }}"
  when: "'ansible' not in item.invocation.module_args.instance_tags.Name"
  changed_when: no
  tags:
    - always
    - provision

- name: Wait for Ansible connection to all hosts
  wait_for_connection:
    delay: 0
    timeout: 400
  when: instances is changed
  delegate_to: "{{ item }}"
  loop: "{{ groups.lab_hosts }}"

- name: Set local username to create on instances
  set_fact:
    username: "{{ item | regex_replace('.*-(\\w*)-\\w*$','\\1') }}"
  with_items: "{{ groups.lab_hosts }}"
  delegate_to: "{{ item }}"
  delegate_facts: yes
  tags:
    - always
    - provision

- name: Generate student inventories
  template:
    src: instances.txt.j2
    dest: ./{{ item.username }}-instances.txt
  with_items: "{{ users }}"
  tags:
    - inventory
    - users
    - user_accounts

- name: Generate instructor inventory
  template:
    src: instructor_inventory.j2
    dest: ./instructor_inventory.txt
  tags:
    - inventory
    - users
    - user_accounts

- name: Generate html page with student details
  template:
    src: index.html.j2
    dest: ./index.html
  tags:
    - inventory
    - users
    - user_accounts
