- name: Generate users list
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  tasks:
    - name: generate users list
      set_fact:
        users: "{{ users|default([]) + [ {'name': 'student' + item, 'username': 'student' + item, 'email': 'student' + item + '@example.com'} ] }}"
      with_sequence: count="{{ student_count }}"
      when: student_count is defined

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  roles:
    - manage_ec2_instances

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  become: yes
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  roles:
    - user_accounts
    - common

- name: Configure control node
  hosts: control_nodes
  become: yes
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  roles:
    - control_node

- name: Email inventory to instructor
  hosts: localhost
  connection: local
  become: no
  gather_facts: no
  vars_files:
    - [ 'vars/custom.yml', 'vars/main.yml' ]
  roles:
    - email-instructor
