---
# install mariadb server
- include_tasks: install.yml
  tags: [install]

# configure root account
- include_tasks: conf_root_access.yml
  tags: [root]

# secure mariadb installation
- include_tasks: secure.yml
  when: mariadb_secure_installation
  tags: [secure]

# create/remove databases
- include_tasks: database.yml
  tags: [database]

# create/remove users
- include_tasks: user_conf.yml
  tags: [user]

