---
- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False
  tags: [secure_anonymous]

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False
  tags: [secure_remote_root]

- name: Remove test db
  mysql_db: 
    name: test 
    state: absent
  tags: [secure_remove_testdb]

- name: Remove access to test db
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True
  tags: [secure_remove_testdb]

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  changed_when: False
  with_items:
    - FLUSH PRIVILEGES
